"""empty message

Revision ID: 808bc12e1fe5
Revises: b1aef99323cb
Create Date: 2018-08-22 18:32:24.696756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808bc12e1fe5'
down_revision = 'b1aef99323cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'is_published')
    # ### end Alembic commands ###
