---
- name: install mysql-server package
  apt:
    name: "{{ packages }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
  loop_control:
    loop_var: packages

