---
- name: Download APP source code
  git:
    repo: 'https://github.com/l769829723/todo.git'
    dest: /app

- name: Install pip requirements
  pip:
    requirements: /app/requirements.txt
    virtualenv: /app/venv
    virtualenv_command: /usr/bin/python3.6 -m venv

- name: Create database for application
  mysql_db:
    name: todo
    state: present
    encoding: utf8

- name: Init the application
  command: source /app/venv/bin/activate.sh && python /app/manage.py db init && python /app/manage.py db upgrade && python /app/manage.py migrate

- name: Running up the application service
  command: nohup python /app/wsgi.py &;